### ISSUE TITLE
Dont buy food

### ISSUE THREAD

**Issue by Ratiboriy** [SmartBotBlack/nftpanda-bot#4]
have error while buy food
![image](https://user-images.githubusercontent.com/89318857/148275945-40adc80c-dfc2-4863-8550-5a8b0c8931b7.png)

**Comment by Ratiboriy** [comment]
i buy food myself, but script feed 1 panda, and instead of feed 2 - script go and buy Sword Part 1 Water

**Comment by frankduque** [comment]
That happens bcs the shop doesn't open in the food page.

You will have to add this 
`document.querySelector(".eat button").click();`

right after this part 
`document.querySelector(".menu-will-be .shop").click();`
